# Generated by Django 4.0.4 on 2022-04-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
