# Generated by Django 4.0.4 on 2022-04-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedbook',
            name='image',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
